### ISSUE TITLE
Question: Database type and engine compatibility?

### ISSUE THREAD

**Issue by fkromer** [jaydenwindle/graphene-subscriptions#13]
Ideally the database type (SQL, NoSQL) and database engine used should not have any impact on the funtionality of `graphene-subscriptions`. However just to make sure, is there any known compatibility issue w.r.t. database engine (database type covered implicitly)?

**Comment by jaydenwindle** [comment]
@fkromer I'm not aware of any compatibility issues, but I haven't done wide testing. `graphene-subscriptions` should work with any database that is supported by the Django ORM, but it may work for other ORMs as well. As long as the ORM implementation that's being used is compatible with Django's JSON serializer and Django signals, then created / updated / deleted subscriptions should work properly.

If you're using another ORM that isn't compatible, you can always handle the sending of events manually since you can pass any JSON-serializable value via Channel Layers.

**Comment by fkromer** [comment]
@jaydenwindle Thanks!
